#!C:\Users\WT194DV\OneDrive - EY\Desktop\MLflow_learn\MLflow_implementation\nenv\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
